# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from duco_control_pkg/LineInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class LineInfo(genpy.Message):
  _md5sum = "c268946f4721487ff5d43b6e4957d2b0"
  _type = "duco_control_pkg/LineInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# LineInfo.msg
geometry_msgs/Point start_point
geometry_msgs/Point end_point
float32 length
float32 angle_deg
float32 distance
int32 type
int32 id
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['start_point','end_point','length','angle_deg','distance','type','id']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','float32','float32','float32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       start_point,end_point,length,angle_deg,distance,type,id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LineInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.start_point is None:
        self.start_point = geometry_msgs.msg.Point()
      if self.end_point is None:
        self.end_point = geometry_msgs.msg.Point()
      if self.length is None:
        self.length = 0.
      if self.angle_deg is None:
        self.angle_deg = 0.
      if self.distance is None:
        self.distance = 0.
      if self.type is None:
        self.type = 0
      if self.id is None:
        self.id = 0
    else:
      self.start_point = geometry_msgs.msg.Point()
      self.end_point = geometry_msgs.msg.Point()
      self.length = 0.
      self.angle_deg = 0.
      self.distance = 0.
      self.type = 0
      self.id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d3f2i().pack(_x.start_point.x, _x.start_point.y, _x.start_point.z, _x.end_point.x, _x.end_point.y, _x.end_point.z, _x.length, _x.angle_deg, _x.distance, _x.type, _x.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_point is None:
        self.start_point = geometry_msgs.msg.Point()
      if self.end_point is None:
        self.end_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 68
      (_x.start_point.x, _x.start_point.y, _x.start_point.z, _x.end_point.x, _x.end_point.y, _x.end_point.z, _x.length, _x.angle_deg, _x.distance, _x.type, _x.id,) = _get_struct_6d3f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d3f2i().pack(_x.start_point.x, _x.start_point.y, _x.start_point.z, _x.end_point.x, _x.end_point.y, _x.end_point.z, _x.length, _x.angle_deg, _x.distance, _x.type, _x.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_point is None:
        self.start_point = geometry_msgs.msg.Point()
      if self.end_point is None:
        self.end_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 68
      (_x.start_point.x, _x.start_point.y, _x.start_point.z, _x.end_point.x, _x.end_point.y, _x.end_point.z, _x.length, _x.angle_deg, _x.distance, _x.type, _x.id,) = _get_struct_6d3f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d3f2i = None
def _get_struct_6d3f2i():
    global _struct_6d3f2i
    if _struct_6d3f2i is None:
        _struct_6d3f2i = struct.Struct("<6d3f2i")
    return _struct_6d3f2i
