# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from duco_control_pkg/ObstacleFlags.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class ObstacleFlags(genpy.Message):
  _md5sum = "d0c938d9c5630fb2581830805df06b63"
  _type = "duco_control_pkg/ObstacleFlags"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ObstacleFlags.msg
# 自定义消息类型，用于发布各区域的避障标志

# 各区域避障标志
bool left_front    # 左前区有障碍
bool left_mid      # 左中区有障碍
bool left_rear     # 左后区有障碍
bool right_front   # 右前区有障碍  
bool right_mid     # 右中区有障碍
bool right_rear    # 右后区有障碍
bool center        # 中区有障碍
bool up            # 上区有障碍
bool down          # 下区有障碍
# 可选：添加时间戳和安全距离信息
time stamp              # 检测时间戳
float32 safe_distance   # 使用的安全距离"""
  __slots__ = ['left_front','left_mid','left_rear','right_front','right_mid','right_rear','center','up','down','stamp','safe_distance']
  _slot_types = ['bool','bool','bool','bool','bool','bool','bool','bool','bool','time','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_front,left_mid,left_rear,right_front,right_mid,right_rear,center,up,down,stamp,safe_distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObstacleFlags, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left_front is None:
        self.left_front = False
      if self.left_mid is None:
        self.left_mid = False
      if self.left_rear is None:
        self.left_rear = False
      if self.right_front is None:
        self.right_front = False
      if self.right_mid is None:
        self.right_mid = False
      if self.right_rear is None:
        self.right_rear = False
      if self.center is None:
        self.center = False
      if self.up is None:
        self.up = False
      if self.down is None:
        self.down = False
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.safe_distance is None:
        self.safe_distance = 0.
    else:
      self.left_front = False
      self.left_mid = False
      self.left_rear = False
      self.right_front = False
      self.right_mid = False
      self.right_rear = False
      self.center = False
      self.up = False
      self.down = False
      self.stamp = genpy.Time()
      self.safe_distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9B2If().pack(_x.left_front, _x.left_mid, _x.left_rear, _x.right_front, _x.right_mid, _x.right_rear, _x.center, _x.up, _x.down, _x.stamp.secs, _x.stamp.nsecs, _x.safe_distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 21
      (_x.left_front, _x.left_mid, _x.left_rear, _x.right_front, _x.right_mid, _x.right_rear, _x.center, _x.up, _x.down, _x.stamp.secs, _x.stamp.nsecs, _x.safe_distance,) = _get_struct_9B2If().unpack(str[start:end])
      self.left_front = bool(self.left_front)
      self.left_mid = bool(self.left_mid)
      self.left_rear = bool(self.left_rear)
      self.right_front = bool(self.right_front)
      self.right_mid = bool(self.right_mid)
      self.right_rear = bool(self.right_rear)
      self.center = bool(self.center)
      self.up = bool(self.up)
      self.down = bool(self.down)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9B2If().pack(_x.left_front, _x.left_mid, _x.left_rear, _x.right_front, _x.right_mid, _x.right_rear, _x.center, _x.up, _x.down, _x.stamp.secs, _x.stamp.nsecs, _x.safe_distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 21
      (_x.left_front, _x.left_mid, _x.left_rear, _x.right_front, _x.right_mid, _x.right_rear, _x.center, _x.up, _x.down, _x.stamp.secs, _x.stamp.nsecs, _x.safe_distance,) = _get_struct_9B2If().unpack(str[start:end])
      self.left_front = bool(self.left_front)
      self.left_mid = bool(self.left_mid)
      self.left_rear = bool(self.left_rear)
      self.right_front = bool(self.right_front)
      self.right_mid = bool(self.right_mid)
      self.right_rear = bool(self.right_rear)
      self.center = bool(self.center)
      self.up = bool(self.up)
      self.down = bool(self.down)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9B2If = None
def _get_struct_9B2If():
    global _struct_9B2If
    if _struct_9B2If is None:
        _struct_9B2If = struct.Struct("<9B2If")
    return _struct_9B2If
