// Generated by gencpp from file key_input_pkg/KeyInput.msg
// DO NOT EDIT!


#ifndef KEY_INPUT_PKG_MESSAGE_KEYINPUT_H
#define KEY_INPUT_PKG_MESSAGE_KEYINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace key_input_pkg
{
template <class ContainerAllocator>
struct KeyInput_
{
  typedef KeyInput_<ContainerAllocator> Type;

  KeyInput_()
    : keys()  {
    }
  KeyInput_(const ContainerAllocator& _alloc)
    : keys(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _keys_type;
  _keys_type keys;





  typedef boost::shared_ptr< ::key_input_pkg::KeyInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::key_input_pkg::KeyInput_<ContainerAllocator> const> ConstPtr;

}; // struct KeyInput_

typedef ::key_input_pkg::KeyInput_<std::allocator<void> > KeyInput;

typedef boost::shared_ptr< ::key_input_pkg::KeyInput > KeyInputPtr;
typedef boost::shared_ptr< ::key_input_pkg::KeyInput const> KeyInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::key_input_pkg::KeyInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::key_input_pkg::KeyInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::key_input_pkg::KeyInput_<ContainerAllocator1> & lhs, const ::key_input_pkg::KeyInput_<ContainerAllocator2> & rhs)
{
  return lhs.keys == rhs.keys;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::key_input_pkg::KeyInput_<ContainerAllocator1> & lhs, const ::key_input_pkg::KeyInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace key_input_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::key_input_pkg::KeyInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::key_input_pkg::KeyInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::key_input_pkg::KeyInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::key_input_pkg::KeyInput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::key_input_pkg::KeyInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::key_input_pkg::KeyInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::key_input_pkg::KeyInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7baccca94a87d2d70852f2dc60f54b65";
  }

  static const char* value(const ::key_input_pkg::KeyInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7baccca94a87d2d7ULL;
  static const uint64_t static_value2 = 0x0852f2dc60f54b65ULL;
};

template<class ContainerAllocator>
struct DataType< ::key_input_pkg::KeyInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "key_input_pkg/KeyInput";
  }

  static const char* value(const ::key_input_pkg::KeyInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::key_input_pkg::KeyInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] keys\n"
;
  }

  static const char* value(const ::key_input_pkg::KeyInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::key_input_pkg::KeyInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.keys);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::key_input_pkg::KeyInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::key_input_pkg::KeyInput_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "keys: ";
    if (v.keys.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.keys.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.keys[i]);
    }
    if (v.keys.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // KEY_INPUT_PKG_MESSAGE_KEYINPUT_H
