// Generated by gencpp from file duco_control_pkg/LineInfo.msg
// DO NOT EDIT!


#ifndef DUCO_CONTROL_PKG_MESSAGE_LINEINFO_H
#define DUCO_CONTROL_PKG_MESSAGE_LINEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace duco_control_pkg
{
template <class ContainerAllocator>
struct LineInfo_
{
  typedef LineInfo_<ContainerAllocator> Type;

  LineInfo_()
    : start_point()
    , end_point()
    , length(0.0)
    , angle_deg(0.0)
    , distance(0.0)
    , type(0)
    , id(0)  {
    }
  LineInfo_(const ContainerAllocator& _alloc)
    : start_point(_alloc)
    , end_point(_alloc)
    , length(0.0)
    , angle_deg(0.0)
    , distance(0.0)
    , type(0)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _start_point_type;
  _start_point_type start_point;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _end_point_type;
  _end_point_type end_point;

   typedef float _length_type;
  _length_type length;

   typedef float _angle_deg_type;
  _angle_deg_type angle_deg;

   typedef float _distance_type;
  _distance_type distance;

   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::duco_control_pkg::LineInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_control_pkg::LineInfo_<ContainerAllocator> const> ConstPtr;

}; // struct LineInfo_

typedef ::duco_control_pkg::LineInfo_<std::allocator<void> > LineInfo;

typedef boost::shared_ptr< ::duco_control_pkg::LineInfo > LineInfoPtr;
typedef boost::shared_ptr< ::duco_control_pkg::LineInfo const> LineInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_control_pkg::LineInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_control_pkg::LineInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_control_pkg::LineInfo_<ContainerAllocator1> & lhs, const ::duco_control_pkg::LineInfo_<ContainerAllocator2> & rhs)
{
  return lhs.start_point == rhs.start_point &&
    lhs.end_point == rhs.end_point &&
    lhs.length == rhs.length &&
    lhs.angle_deg == rhs.angle_deg &&
    lhs.distance == rhs.distance &&
    lhs.type == rhs.type &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_control_pkg::LineInfo_<ContainerAllocator1> & lhs, const ::duco_control_pkg::LineInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_control_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duco_control_pkg::LineInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_control_pkg::LineInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_control_pkg::LineInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_control_pkg::LineInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_control_pkg::LineInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_control_pkg::LineInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_control_pkg::LineInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c268946f4721487ff5d43b6e4957d2b0";
  }

  static const char* value(const ::duco_control_pkg::LineInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc268946f4721487fULL;
  static const uint64_t static_value2 = 0xf5d43b6e4957d2b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_control_pkg::LineInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_control_pkg/LineInfo";
  }

  static const char* value(const ::duco_control_pkg::LineInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_control_pkg::LineInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# LineInfo.msg\n"
"geometry_msgs/Point start_point\n"
"geometry_msgs/Point end_point\n"
"float32 length\n"
"float32 angle_deg\n"
"float32 distance\n"
"int32 type\n"
"int32 id\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::duco_control_pkg::LineInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_control_pkg::LineInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_point);
      stream.next(m.end_point);
      stream.next(m.length);
      stream.next(m.angle_deg);
      stream.next(m.distance);
      stream.next(m.type);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_control_pkg::LineInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_control_pkg::LineInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "start_point: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.start_point);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_point: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.end_point);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle_deg: ";
    Printer<float>::stream(s, indent + "  ", v.angle_deg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_CONTROL_PKG_MESSAGE_LINEINFO_H
