// Generated by gencpp from file duco_control_pkg/LineDetectionArray.msg
// DO NOT EDIT!


#ifndef DUCO_CONTROL_PKG_MESSAGE_LINEDETECTIONARRAY_H
#define DUCO_CONTROL_PKG_MESSAGE_LINEDETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <duco_control_pkg/LineInfo.h>

namespace duco_control_pkg
{
template <class ContainerAllocator>
struct LineDetectionArray_
{
  typedef LineDetectionArray_<ContainerAllocator> Type;

  LineDetectionArray_()
    : header()
    , lines()  {
    }
  LineDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lines(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::duco_control_pkg::LineInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::duco_control_pkg::LineInfo_<ContainerAllocator> >> _lines_type;
  _lines_type lines;





  typedef boost::shared_ptr< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct LineDetectionArray_

typedef ::duco_control_pkg::LineDetectionArray_<std::allocator<void> > LineDetectionArray;

typedef boost::shared_ptr< ::duco_control_pkg::LineDetectionArray > LineDetectionArrayPtr;
typedef boost::shared_ptr< ::duco_control_pkg::LineDetectionArray const> LineDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator1> & lhs, const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lines == rhs.lines;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator1> & lhs, const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_control_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f0d2b557aa2d2c956b6c6a0f2991a99";
  }

  static const char* value(const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f0d2b557aa2d2c9ULL;
  static const uint64_t static_value2 = 0x56b6c6a0f2991a99ULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_control_pkg/LineDetectionArray";
  }

  static const char* value(const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# LineDetectionArray.msg\n"
"std_msgs/Header header\n"
"duco_control_pkg/LineInfo[] lines # 包含多条 LineInfo 消息\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: duco_control_pkg/LineInfo\n"
"# LineInfo.msg\n"
"geometry_msgs/Point start_point\n"
"geometry_msgs/Point end_point\n"
"float32 length\n"
"float32 angle_deg\n"
"float32 distance\n"
"int32 type\n"
"int32 id\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lines);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_control_pkg::LineDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_control_pkg::LineDetectionArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lines: ";
    if (v.lines.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::duco_control_pkg::LineInfo_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.lines[i]);
    }
    if (v.lines.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_CONTROL_PKG_MESSAGE_LINEDETECTIONARRAY_H
