// Generated by gencpp from file duco_control_pkg/ObstacleFlags.msg
// DO NOT EDIT!


#ifndef DUCO_CONTROL_PKG_MESSAGE_OBSTACLEFLAGS_H
#define DUCO_CONTROL_PKG_MESSAGE_OBSTACLEFLAGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duco_control_pkg
{
template <class ContainerAllocator>
struct ObstacleFlags_
{
  typedef ObstacleFlags_<ContainerAllocator> Type;

  ObstacleFlags_()
    : left_front(false)
    , left_mid(false)
    , left_rear(false)
    , right_front(false)
    , right_mid(false)
    , right_rear(false)
    , center(false)
    , up(false)
    , down(false)
    , stamp()
    , safe_distance(0.0)  {
    }
  ObstacleFlags_(const ContainerAllocator& _alloc)
    : left_front(false)
    , left_mid(false)
    , left_rear(false)
    , right_front(false)
    , right_mid(false)
    , right_rear(false)
    , center(false)
    , up(false)
    , down(false)
    , stamp()
    , safe_distance(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _left_front_type;
  _left_front_type left_front;

   typedef uint8_t _left_mid_type;
  _left_mid_type left_mid;

   typedef uint8_t _left_rear_type;
  _left_rear_type left_rear;

   typedef uint8_t _right_front_type;
  _right_front_type right_front;

   typedef uint8_t _right_mid_type;
  _right_mid_type right_mid;

   typedef uint8_t _right_rear_type;
  _right_rear_type right_rear;

   typedef uint8_t _center_type;
  _center_type center;

   typedef uint8_t _up_type;
  _up_type up;

   typedef uint8_t _down_type;
  _down_type down;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef float _safe_distance_type;
  _safe_distance_type safe_distance;





  typedef boost::shared_ptr< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleFlags_

typedef ::duco_control_pkg::ObstacleFlags_<std::allocator<void> > ObstacleFlags;

typedef boost::shared_ptr< ::duco_control_pkg::ObstacleFlags > ObstacleFlagsPtr;
typedef boost::shared_ptr< ::duco_control_pkg::ObstacleFlags const> ObstacleFlagsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator1> & lhs, const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator2> & rhs)
{
  return lhs.left_front == rhs.left_front &&
    lhs.left_mid == rhs.left_mid &&
    lhs.left_rear == rhs.left_rear &&
    lhs.right_front == rhs.right_front &&
    lhs.right_mid == rhs.right_mid &&
    lhs.right_rear == rhs.right_rear &&
    lhs.center == rhs.center &&
    lhs.up == rhs.up &&
    lhs.down == rhs.down &&
    lhs.stamp == rhs.stamp &&
    lhs.safe_distance == rhs.safe_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator1> & lhs, const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duco_control_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0c938d9c5630fb2581830805df06b63";
  }

  static const char* value(const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0c938d9c5630fb2ULL;
  static const uint64_t static_value2 = 0x581830805df06b63ULL;
};

template<class ContainerAllocator>
struct DataType< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duco_control_pkg/ObstacleFlags";
  }

  static const char* value(const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ObstacleFlags.msg\n"
"# 自定义消息类型，用于发布各区域的避障标志\n"
"\n"
"# 各区域避障标志\n"
"bool left_front    # 左前区有障碍\n"
"bool left_mid      # 左中区有障碍\n"
"bool left_rear     # 左后区有障碍\n"
"bool right_front   # 右前区有障碍  \n"
"bool right_mid     # 右中区有障碍\n"
"bool right_rear    # 右后区有障碍\n"
"bool center        # 中区有障碍\n"
"bool up            # 上区有障碍\n"
"bool down          # 下区有障碍\n"
"# 可选：添加时间戳和安全距离信息\n"
"time stamp              # 检测时间戳\n"
"float32 safe_distance   # 使用的安全距离\n"
;
  }

  static const char* value(const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_front);
      stream.next(m.left_mid);
      stream.next(m.left_rear);
      stream.next(m.right_front);
      stream.next(m.right_mid);
      stream.next(m.right_rear);
      stream.next(m.center);
      stream.next(m.up);
      stream.next(m.down);
      stream.next(m.stamp);
      stream.next(m.safe_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleFlags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duco_control_pkg::ObstacleFlags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duco_control_pkg::ObstacleFlags_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "left_front: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_front);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_mid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_mid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_rear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_rear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_front: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_front);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_mid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_mid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_rear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_rear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.center);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "up: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.up);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.down);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "safe_distance: ";
    Printer<float>::stream(s, indent + "  ", v.safe_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCO_CONTROL_PKG_MESSAGE_OBSTACLEFLAGS_H
